blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://cambiomlworkspace.slack.com/join/shared_invite/zt-1zes33rmt-20Rag043uvExUaUdvt5_xQ#/shared-invite/email
    about: Ask questions and discuss with other CambioML community members